### ISSUE TITLE
Improve error-handling in config-reader

### ISSUE THREAD

**Issue by fr3dch3n** [fr3dch3n/git-hooks#3]
Right now, the config-reader panics on invalid fields, e. g.:
```yaml
regex: "\\[.+?\\]\\s(.*?)\\s.*"
separator: "|"
me: 
team:
  - short: hug
    name: Hugo Heimlich
    email: hugo.heimlich@domain.com
```

The empty field `me` panics:
`thread 'config::read_config::test_read_test_config' panicked at 'called Option::unwrap() on a None value'`.

It should print a helpful error-message for invalid configuration.
